# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgV_WDk2N1qRi7nNfKBIbExCjgoa2B2V
"""

#LECTURA DE DATOS
#Ingresar las 3 notas
n1 = int(input('Ingrese la primera nota:'))
n2 = int(input('Ingrese la segunda nota:'))
n3 = int(input('Ingrese la tercera nota:'))


#PROCESO
#Calculamos el promedio
promedio = (n1 + n2 + n3)/3

#Evaluamos la condición "Aprobado (<=11) o Desaprobado"
if promedio >= 11:
  mje = "El estudiante aprobó"
else:
  mje = "El estudiante no aprobó"


#RESULTADOS
#Mostramos los resultados
print("El promedio del estudiante es ", promedio)
print(mje)